### PR TITLE
add Starman dependency

### PR DESCRIPTION
**Pull request by komarov**
Hi!
Now it is possible to install Ubic::Service::Starman without Starman itself being installed.

### CODE REVIEW

**Comment by throughnothing** [comment]
I don't n kw if I want to make `Starman` a dependency since you can override the executable it runs with sub `UBIC_SERVICE_PLACKUP_BIN`, but I'm not sure that being able to change it is that useful anyway.

**Comment by throughnothing** [comment]
And the proper way to add the `Starman` dependency if we go that route is to add it to dist.ini since that auto-generates the `Makefile.PL`

**Comment by komarov** [comment]
Well, I haven't considered this.
But why would one prefer Ubic::Service::Starman to Ubic::Service::Plack then?

Sorry, I'm not familiar with dist.ini

**Comment by throughnothing** [comment]
The main reason for this is just to give you `reload` which lets starman (or whatever else you use) reload gracefully without any dropped connections.  I think you're right and it probably should be made a dep.  I'll add it to the dist.ini in a little but.

**Comment by komarov** [comment]
Thanks!

**Comment by throughnothing** [comment]
I just pulled your change (with a modification to the `dist.ini`) and released to CPAN:

https://github.com/throughnothing/Ubic-Service-Starman/commit/cf9a5cc803dbaba0db68f1ddacd816c63fd80a95

Thanks!

**Pull request closed without merging**
